### ISSUE TITLE
White text on Survival bsModal

### ISSUE THREAD

**Issue by jasdumas** [jasdumas/GEO-AWS#13]
I don't get any other errors and I'm using the iris data set asa placeholder.

![white-text-error](https://cloud.githubusercontent.com/assets/6685750/8509534/137e2fa6-2276-11e5-827b-eb5ec23f2f34.jpg)

**Comment by gdancik** [comment]
This is because of the font color specified by the CSS code. Specifically, the following code in mainPanel.R sets the font color to white in several places (including the bsModal table):

tags$style(type = "text/css",
             ".well{color: white; background-color: black}"
  ),

If you comment this out, the font color for the table will be black. 

I initially added this to change the background color and font for the sidebarPanel. Several elements in Shiny seem to depend on the "well" class, so this CSS code effects several of them.

**Comment by jasdumas** [comment]
Ok - the most recent commit addresses this for the time being!
